baseurl: https://cass-art.netlify.app/
title: Cass Mess
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2021 Cassandra Pengelly'
  description: Art portfolio
  email: you@yoursite.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Writing
      url: post/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - Hi! I'm Cass; here is where I make my creative mess.
    - Currently based in Stellenbosch, South Africa.
  social:
    #email: email@example.com
    #facebook: full page or profile url in facebook
    github: https://github.com/cass-code
    #gitlab: full profile url in gitlab
    #googleplus: full profile url in googleplus
    instagram: https://www.instagram.com/cass.mess/
    linkedin: https://www.linkedin.com/in/cassandra-pengelly/
    #stackoverflow: full profile url in stackoverflow
    #twitter: full profile url in twitter
    #whatsapp: wa.me service link
    #youtube: full profile url in youtube
  style: default
